### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by ElPumpo** [Council-of-the-Delverers/Dungeons-and-Delving#1]
# TODO
- [ ] sound assets
    - [ ] `alertSound`
    - [x] `attackSound`
    - [ ] `dieSound`
    - [x] `hurtSound`
    - [ ] `idleSound`
    - [ ] various `dropSound` and `pickupSound`
    - [ ] various `ui_dialogue_open`
    - [ ] various `ui_dialogue_close`
    - [ ] starting to sprint, and ending sprint
- [ ] balance stuff
    - [ ] balance monsters and other creatures #5 
    - [ ] balance items
- [ ] work on dungeon overhaul
- [ ] add information to wiki #8
    - [ ] creatures
        - [ ] underlands creatures
    - [ ] images
        - [ ] preview images of the accual mod
 - [ ] ask devs for source code? because decompilers can only do so much...
    - [ ] integrate currency UI in the inventory
